=== dblevins/jaxb-tck/xml_schema/tests/xml_schema/sunData/SType/ST_facets/ST_facets00501m/ST_facets00501m9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<!--
Ident: @(#)ST_facets00501m9.xsd
   generated from: @(#)ST_facets00501m.jmpp	1.3 02/11/14

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="SType/ST_facets"
    targetNamespace="SType/ST_facets">

    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded">
                <xsd:element name="value" type="S"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="S">
        <xsd:restriction base="xsd:NCName">
            <xsd:enumeration value="a00એ"/>
            <xsd:enumeration value="a0-ઐ"/>
            <xsd:enumeration value="a0Aઑ"/>
            <xsd:enumeration value="a10ઓ"/>
            <xsd:enumeration value="a1-ઝ"/>
            <xsd:enumeration value="a1Aન"/>
            <xsd:enumeration value="a20પ"/>
            <xsd:enumeration value="a2-ભ"/>
            <xsd:enumeration value="a2Aર"/>
            <xsd:enumeration value="a30લ"/>
            <xsd:enumeration value="a3-લ"/>
            <xsd:enumeration value="a3Aળ"/>
            <xsd:enumeration value="a40વ"/>
            <xsd:enumeration value="a4-ષ"/>
            <xsd:enumeration value="a4Aહ"/>
            <xsd:enumeration value="a50ઽ"/>
            <xsd:enumeration value="a60ૠ"/>
            <xsd:enumeration value="a70ଅ"/>
            <xsd:enumeration value="a7-ଈ"/>
            <xsd:enumeration value="a7Aଌ"/>
            <xsd:enumeration value="a80ଏ"/>
            <xsd:enumeration value="a8-ଏ"/>
            <xsd:enumeration value="a8Aଐ"/>
            <xsd:enumeration value="a90ଓ"/>
            <xsd:enumeration value="a9-ଝ"/>
            <xsd:enumeration value="a9Aନ"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== dblevins/jaxb-tck/xml_schema/tests/xml_schema/sunData/SType/ST_facets/ST_facets00501m/ST_facets00501m9_p.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<!--
Ident: @(#)ST_facets00501m9_p.xml
   generated from: @(#)ST_facets00501m.jmpp	1.3 02/11/14

-->

<test:root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:test="SType/ST_facets"
    xsi:schemaLocation="SType/ST_facets ST_facets00501m9.xsd">
    <value>a00એ</value>
    <value>a0-ઐ</value>
    <value>a0Aઑ</value>
    <value>a10ઓ</value>
    <value>a1-ઝ</value>
    <value>a1Aન</value>
    <value>a20પ</value>
    <value>a2-ભ</value>
    <value>a2Aર</value>
    <value>a30લ</value>
    <value>a3-લ</value>
    <value>a3Aળ</value>
    <value>a40વ</value>
    <value>a4-ષ</value>
    <value>a4Aહ</value>
    <value>a50ઽ</value>
    <value>a60ૠ</value>
    <value>a70ଅ</value>
    <value>a7-ଈ</value>
    <value>a7Aଌ</value>
    <value>a80ଏ</value>
    <value>a8-ଏ</value>
    <value>a8Aଐ</value>
    <value>a90ଓ</value>
    <value>a9-ଝ</value>
    <value>a9Aନ</value>
</test:root>
